import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { animate, stagger } from 'animejs';
import { ArrowUpRight, ChevronRight } from 'lucide-react';
import IndiaMap from '../components/IndiaMap';
import SystemCard from '../components/SystemCard';
import Footer from '../components/Footer';
import { useSystems } from '../hooks/useSystems';

export default function HomePage() {
  const hero = useRef(null);
  const { systems:featured, pagination, loading, error } = useSystems({ limit:3 });
  useEffect(() => { animate(hero.current.querySelectorAll('.reveal'), { opacity:[0,1], translateY:[20,0], delay:stagger(110,{start:120}), duration:700, ease:'outExpo' }); }, []);
  return <>{error && <p className="api-notice">{error}</p>}<section className="hero" ref={hero}><div className="hero-copy"><p className="eyebrow reveal">A digital archive of indigenous water wisdom</p><h1 className="reveal">Water holds<br/><em>memory.</em></h1><p className="lede reveal">Discover the ingenious systems that have sustained communities across India for centuries.</p><div className="hero-actions reveal"><Link to="/archive" className="btn primary">Explore the archive <ArrowUpRight size={17}/></Link><a href="#map" className="text-link">View the map <ChevronRight size={16}/></a></div></div><div className="hero-visual"><div className="sun"/><div className="arch-stack">{featured.map((system,index) => <motion.div key={system.id} className={`arch-card arch-card-${index+1}`} initial={{opacity:0,x:index===0?26:18+index*8,y:24+index*20,rotate:index===0?-5:index===1?4:-2}} animate={{opacity:1,x:0,y:0,rotate:0}} transition={{duration:.6,delay:.18+index*.12,ease:[.16,1,.3,1]}} whileHover={{y:-10,scale:1.02,transition:{duration:.2}}}><Link to={`/archive/${system.id}`} className="arch-card-link"><span className="mono">{system.state} · {String(index+1).padStart(2,'0')}</span><img src={system.image} alt={system.name}/><div className="arch-caption"><span>{system.name}</span><ArrowUpRight size={17}/></div></Link></motion.div>)}</div><div className="water-line"/></div></section><section className="intro"><p className="eyebrow">A shared inheritance</p><h2>Ingenious systems, shaped by land and community.</h2><p>From the geometric depths of baoris to the living networks of eris, India’s water heritage tells a story of resilience, reciprocity and care.</p><div className="stat-row"><div><strong>{pagination?.total ?? (loading ? '…' : 0)}</strong><span>systems archived</span></div><div><strong>32</strong><span>states represented</span></div><div><strong>1000+</strong><span>years of knowledge</span></div></div></section><section className="map-section" id="map"><div className="section-top"><div><p className="eyebrow">Explore by place</p><h2>A country of water<br/><em>cultures.</em></h2></div><p>Browse the archive to trace systems rooted in each landscape.</p></div><IndiaMap interactive systems={featured}/><Link to="/archive" className="text-link map-link">See all water systems <ArrowUpRight size={16}/></Link></section><section className="featured"><div className="section-top"><div><p className="eyebrow">From the archive</p><h2>Stories beneath<br/>the surface.</h2></div><Link to="/archive" className="text-link">Browse all <ArrowUpRight size={16}/></Link></div><div className="card-grid">{featured.map((system,index) => <SystemCard key={system.id} system={system} index={index}/>)}</div></section><Footer/></>;
}
